# https://taskfile.dev/#/installation
version: 3

tasks:
  dev: dub build
  build: dub build --build=release

  format: dub run dfmt -- --inplace ./emend ./script

  lint: dub lint

  clean:
    - dub clean
    - '
      {{if eq OS "windows"}} powershell -C "
      if (test-path ./emend/ts/gen) { rm -r -force ./emend/ts/gen }
      if (test-path ./emend/ts/build) { rm -r -force ./emend/ts/build }
      if (test-path ./emend/build) { rm -r -force ./emend/build }
      if (test-path ./emend/ts/libc.d) { rm -force ./emend/ts/libc.d }"
      {{else}}
      rm -rf ./emend/ts/gen ./emend/ts/build ./emend/build ./.dub ./emend/ts/libc.d {{end}}
      '
