# https://taskfile.dev/#/installation
version: 3

tasks:
  dev: dub build
  build: dub build --build=release

  format: dub run dfmt -- --inplace ./src ./script

  lint: dub lint

  clean:
    - dub clean
    - '
      {{if eq OS "windows"}} powershell -C "
      if (test-path ./src/ts/gen) { rm -r -force ./src/ts/gen }
      if (test-path ./src/ts/build) { rm -r -force ./src/ts/build }
      if (test-path ./src/build) { rm -r -force ./src/build }
      if (test-path ./src/ts/libc.d) { rm -force ./src/ts/libc.d }"
      {{else}}
      rm -rf ./src/ts/gen ./src/ts/build ./src/build ./.dub ./src/ts/libc.d {{end}}
      '
